language: haxe

haxe:
  - stable

hxml:
  - test.hxml
  # Install hxcpp:
  - hxml/test.cpp.hxml
  - example.hxml

script:
  - haxe hxml/test.neko.hxml
  - haxe hxml/test.cpp.hxml
  - neko out/neko/test.n
  - ./out/cpp/TestAll
  - haxe example.hxml
